import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Navbar from '../components/common/Navbar';
import Footer from '../components/common/Footer';
import { FiArrowRight, FiMic, FiCode, FiBarChart2, FiAward, FiStar } from 'react-icons/fi';

const features = [
  { icon: FiMic, title: 'AI-Powered Interviews', desc: 'Practice with intelligent questions generated by Google Gemini AI tailored to your skill level.', color: 'from-purple-500 to-indigo-500' },
  { icon: FiCode, title: 'Coding Challenges', desc: 'Solve real interview coding problems with Monaco editor and get AI code reviews instantly.', color: 'from-cyan-500 to-blue-500' },
  { icon: FiBarChart2, title: 'Performance Analytics', desc: 'Track your progress with detailed charts, skill analysis, and personalized improvement plans.', color: 'from-green-500 to-teal-500' },
  { icon: FiAward, title: 'Resume-Based Questions', desc: 'Upload your resume and get interview questions tailored specifically to your experience.', color: 'from-orange-500 to-red-500' },
];

const stats = [
  { value: '50K+', label: 'Practice Sessions' },
  { value: '200+', label: 'Interview Questions' },
  { value: '95%', label: 'User Satisfaction' },
  { value: '30+', label: 'Job Categories' },
];

const testimonials = [
  { name: 'Ahmed Hassan', role: 'Frontend Developer at Google', text: 'This platform helped me ace my Google interview. The AI feedback was incredibly detailed and accurate!', rating: 5 },
  { name: 'Sara Khan', role: 'Data Scientist at Microsoft', text: 'The voice interview mode felt like a real interview. I gained so much confidence practicing here.', rating: 5 },
  { name: 'Ali Raza', role: 'Full Stack Dev at Amazon', text: 'The coding challenges and AI review system are top-notch. Highly recommended for serious prep!', rating: 5 },
];

const Home = () => {
  return (
    <div className="min-h-screen bg-white dark:bg-dark-900">
      <Navbar />

      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-32 px-6">
        {/* Animated background */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-primary-500/20 rounded-full blur-3xl animate-pulse-slow" />
          <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-accent-500/20 rounded-full blur-3xl animate-pulse-slow" style={{ animationDelay: '1s' }} />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-purple-500/10 rounded-full blur-3xl" />
        </div>

        <div className="relative max-w-7xl mx-auto text-center">
          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <div className="inline-flex items-center gap-2 bg-primary-50 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 px-4 py-2 rounded-full text-sm font-semibold mb-6 border border-primary-200 dark:border-primary-800">
              <FiStar size={14} />
              AI-Powered Interview Preparation Platform
            </div>
            <h1 className="text-5xl md:text-7xl font-black text-gray-900 dark:text-white mb-6 leading-tight tracking-tight">
              Land Your{' '}
              <span className="gradient-text">Dream Job</span>
              <br />With AI Practice
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto mb-10 leading-relaxed">
              Practice technical and HR interviews with AI-generated questions, get instant feedback, solve coding challenges, and track your progress — all in one platform.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/register" className="btn-primary text-lg px-8 py-4 flex items-center justify-center gap-2">
                Start Free Practice <FiArrowRight />
              </Link>
              <Link to="/about" className="btn-ghost text-lg px-8 py-4">
                Learn More
              </Link>
            </div>
          </motion.div>

          {/* Stats */}
          <motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.2 }}
            className="grid grid-cols-2 md:grid-cols-4 gap-6 mt-20 max-w-4xl mx-auto">
            {stats.map(({ value, label }) => (
              <div key={label} className="glass-card text-center">
                <div className="text-3xl font-black gradient-text">{value}</div>
                <div className="text-sm text-gray-500 dark:text-gray-400 font-medium mt-1">{label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-6 bg-gray-50 dark:bg-dark-800">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-gray-900 dark:text-white mb-4">Everything You Need to <span className="gradient-text">Succeed</span></h2>
            <p className="text-gray-500 dark:text-gray-400 text-lg max-w-2xl mx-auto">A complete suite of AI-powered tools to prepare you for any interview scenario.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map(({ icon: Icon, title, desc, color }, i) => (
              <motion.div key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}
                className="card p-6 hover:shadow-xl transition-all duration-300 group">
                <div className={`w-12 h-12 bg-gradient-to-br ${color} rounded-xl flex items-center justify-center mb-4 shadow-lg group-hover:scale-110 transition-transform`}>
                  <Icon className="text-white" size={22} />
                </div>
                <h3 className="font-bold text-gray-900 dark:text-white mb-2">{title}</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">{desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-6">
        <div className="max-w-5xl mx-auto text-center">
          <h2 className="text-4xl font-black text-gray-900 dark:text-white mb-4">How It <span className="gradient-text">Works</span></h2>
          <p className="text-gray-500 dark:text-gray-400 text-lg mb-16">Get interview-ready in 3 simple steps.</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { step: '01', title: 'Create Account', desc: 'Sign up free and set your target role and skill level in minutes.' },
              { step: '02', title: 'Practice Daily', desc: 'Choose your category, start AI interviews or coding challenges, and get instant feedback.' },
              { step: '03', title: 'Track & Improve', desc: 'Review analytics, identify weak areas, and watch your scores improve over time.' },
            ].map(({ step, title, desc }) => (
              <div key={step} className="relative">
                <div className="text-6xl font-black gradient-text mb-4 opacity-30">{step}</div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">{title}</h3>
                <p className="text-gray-500 dark:text-gray-400">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-24 px-6 bg-gray-50 dark:bg-dark-800">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-4xl font-black text-center text-gray-900 dark:text-white mb-4">Loved by <span className="gradient-text">Developers</span></h2>
          <p className="text-center text-gray-500 dark:text-gray-400 mb-12">See what our users say about their interview success</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map(({ name, role, text, rating }) => (
              <div key={name} className="card p-6">
                <div className="flex gap-1 mb-4">{[...Array(rating)].map((_, i) => <FiStar key={i} className="text-yellow-400 fill-yellow-400" size={16} />)}</div>
                <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed mb-4">"{text}"</p>
                <div>
                  <p className="font-semibold text-gray-900 dark:text-white text-sm">{name}</p>
                  <p className="text-xs text-primary-500">{role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 bg-gradient-to-br from-primary-600 via-primary-700 to-accent-600">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-4xl font-black text-white mb-4">Ready to Ace Your Interview?</h2>
          <p className="text-primary-200 text-lg mb-8">Join thousands of developers who landed their dream jobs using AI Interview Prep.</p>
          <Link to="/register" className="inline-flex items-center gap-2 bg-white text-primary-700 font-bold px-8 py-4 rounded-xl hover:shadow-2xl hover:scale-[1.02] transition-all duration-200 text-lg">
            Start Practicing Free <FiArrowRight />
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Home;
