console.log("🔥 GEMINI KEY:", process.env.GEMINI_API_KEY);

const { GoogleGenerativeAI } = require('@google/generative-ai');

// Initialize Gemini only if key is provided and not a placeholder
const isKeyValid = process.env.GEMINI_API_KEY && 
                   process.env.GEMINI_API_KEY !== 'your_gemini_api_key_here' &&
                   !process.env.GEMINI_API_KEY.includes('your_');

const genAI = isKeyValid ? new GoogleGenerativeAI(process.env.GEMINI_API_KEY) : null;

/**
 * Helper to extract and parse JSON from AI response
 */
const parseAIResponse = (text, isArray = false) => {
  try {
    const startChar = isArray ? '[' : '{';
    const endChar = isArray ? ']' : '}';
    const jsonStart = text.indexOf(startChar);
    const jsonEnd = text.lastIndexOf(endChar) + 1;
    
    if (jsonStart === -1 || jsonEnd === 0) {
      throw new Error('No valid JSON found in AI response');
    }

    const jsonStr = text.slice(jsonStart, jsonEnd);
    return JSON.parse(jsonStr);
  } catch (error) {
    console.error('❌ AI JSON Parse Error:', error.message);
    console.log('📄 Raw Response:', text);
    throw new Error('Failed to parse AI response. Please try again.');
  }
};

/**
 * Generate interview questions using Gemini AI
 */
const generateInterviewQuestions = async ({ category, difficulty, type, count = 10 }) => {
  if (!genAI) {
    console.log('⚠️ Using MOCK data for Interview Questions (No API Key)');
    return Array(count).fill(0).map((_, i) => ({
      text: `Mock Question ${i + 1} for ${category} (${difficulty})`,
      expectedAnswer: 'This is a sample answer generated in mock mode.',
      tags: [category.toLowerCase(), difficulty.toLowerCase()]
    }));
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    const prompt = `You are an expert technical interviewer. Generate exactly ${count} ${difficulty} level ${type} interview questions for the category: "${category}".
    Return ONLY a valid JSON array. No markdown, no explanations. Format:
    [
      {
        "text": "Question text here",
        "expectedAnswer": "Brief expected answer or key points",
        "tags": ["tag1", "tag2"]
      }
    ]`;

    const result = await model.generateContent(prompt);
    return parseAIResponse(result.response.text().trim(), true);
  } catch (error) {
    console.error('❌ Gemini Error (Questions):', error.message);
    throw error;
  }
};

/**
 * Analyze an interview answer and provide feedback
 */
const analyzeAnswer = async ({ question, answer, category, difficulty }) => {
  if (!genAI) {
    console.log('⚠️ Using MOCK data for Answer Analysis (No API Key)');
    return {
      score: 85,
      grammar: 90,
      technicalCorrectness: 80,
      communication: 85,
      confidence: 90,
      relevance: 100,
      clarity: 85,
      summary: "This is a mock evaluation because no Gemini API key was found.",
      strengths: ["Clear structure", "Direct answer"],
      improvements: ["Add more technical details", "Give real-world examples"],
      suggestedAnswer: "In a real scenario, this would be the ideal answer generated by AI."
    };
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    const prompt = `You are an expert interviewer evaluating a candidate's answer. Analyze the following:
    Category: ${category}
    Difficulty: ${difficulty}
    Question: ${question}
    Candidate's Answer: ${answer}

    Provide a comprehensive evaluation. Return ONLY valid JSON (no markdown):
    {
      "score": <number 0-100>,
      "grammar": <number 0-100>,
      "technicalCorrectness": <number 0-100>,
      "communication": <number 0-100>,
      "confidence": <number 0-100>,
      "relevance": <number 0-100>,
      "clarity": <number 0-100>,
      "summary": "<2-3 sentence evaluation>",
      "strengths": ["strength1", "strength2"],
      "improvements": ["improvement1", "improvement2"],
      "suggestedAnswer": "<ideal answer or key points>"
    }`;

    const result = await model.generateContent(prompt);
    return parseAIResponse(result.response.text().trim());
  } catch (error) {
    console.error('❌ Gemini Error (Analysis):', error.message);
    throw error;
  }
};

/**
 * Review submitted code
 */
const reviewCode = async ({ code, language, challengeTitle, challengeDescription }) => {
  if (!genAI) {
    console.log('⚠️ Using MOCK data for Code Review (No API Key)');
    return {
      score: 75,
      timeComplexity: "O(n)",
      spaceComplexity: "O(1)",
      correctness: "The solution seems correct for basic cases.",
      codeQuality: "Good readability but could be optimized.",
      suggestions: ["Use more descriptive names", "Add error handling"],
      bugs: [],
      summary: "This is a mock code review generated because no Gemini API key was found."
    };
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    const prompt = `You are an expert code reviewer. Review this ${language} code solution:
    Challenge: ${challengeTitle}
    Description: ${challengeDescription}
    Code: \`\`\`${language}\n${code}\n\`\`\`

    Return ONLY valid JSON (no markdown):
    {
      "score": <number 0-100>,
      "timeComplexity": "<Big O notation>",
      "spaceComplexity": "<Big O notation>",
      "correctness": "<assessment of correctness>",
      "codeQuality": "<assessment of code quality>",
      "suggestions": ["suggestion1", "suggestion2"],
      "bugs": ["bug1 if any"],
      "summary": "<overall review summary>"
    }`;

    const result = await model.generateContent(prompt);
    return parseAIResponse(result.response.text().trim());
  } catch (error) {
    console.error('❌ Gemini Error (Code Review):', error.message);
    throw error;
  }
};

/**
 * Generate questions from resume skills
 */
const generateQuestionsFromResume = async ({ skills, experience, targetRole }) => {
  if (!genAI) {
    console.log('⚠️ Using MOCK data for Resume Questions (No API Key)');
    return [{
      text: `Mock Question based on your skill: ${skills[0] || 'Software Development'}`,
      skill: skills[0] || 'General',
      difficulty: 'Intermediate',
      type: 'Technical',
      expectedAnswer: 'Sample key points for resume-based question.'
    }];
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    const prompt = `Based on this candidate's profile, generate targeted interview questions:
    Skills: ${skills.join(', ')}
    Experience Level: ${experience}
    Target Role: ${targetRole || 'Software Developer'}

    Generate 15 interview questions tailored to their skills. Return ONLY valid JSON array:
    [
      {
        "text": "Question text",
        "skill": "related skill",
        "difficulty": "Beginner|Intermediate|Advanced",
        "type": "Technical|HR",
        "expectedAnswer": "key points"
      }
    ]`;

    const result = await model.generateContent(prompt);
    return parseAIResponse(result.response.text().trim(), true);
  } catch (error) {
    console.error('❌ Gemini Error (Resume):', error.message);
    throw error;
  }
};

/**
 * Generate career suggestions
 */
const generateCareerSuggestions = async ({ weakAreas, strongAreas, targetRole }) => {
  if (!genAI) {
    return {
      summary: "Focus on improving your weak areas while leveraging your strengths.",
      priorityImprovements: weakAreas.slice(0, 2),
      learningResources: [{ topic: "General Web Dev", resource: "MDN Web Docs" }],
      nextSteps: ["Build a portfolio project", "Practice mock interviews"],
      estimatedReadiness: "70%"
    };
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    const prompt = `As a career coach, provide personalized suggestions for a developer:
    Strong Areas: ${strongAreas.join(', ')}
    Weak Areas: ${weakAreas.join(', ')}
    Target Role: ${targetRole}

    Return ONLY valid JSON (no markdown):
    {
      "summary": "<personalized career advice>",
      "priorityImprovements": ["area1", "area2"],
      "learningResources": [{"topic": "...", "resource": "..."}],
      "nextSteps": ["step1", "step2", "step3"],
      "estimatedReadiness": "<percentage ready for target role>"
    }`;

    const result = await model.generateContent(prompt);
    return parseAIResponse(result.response.text().trim());
  } catch (error) {
    console.error('❌ Gemini Error (Career):', error.message);
    throw error;
  }
};

module.exports = {
  generateInterviewQuestions,
  analyzeAnswer,
  reviewCode,
  generateQuestionsFromResume,
  generateCareerSuggestions
};
